//! Generated from examples/sqlparse/keywords.py SQL_REGEX (do not hand-edit).
//! Each rule: (pattern, action). action None = PROCESS_AS_KEYWORD (keyword lookup).
//! Patterns are applied with `(?i)` (re.IGNORECASE) and fancy-regex semantics.

use crate::tokens::TokenType;

pub const RULES: &[(&str, Option<TokenType>)] = &[
    ("(--|# )\\+.*?(\\r\\n|\\r|\\n|$)", Some(&["Comment", "Single", "Hint"])),
    ("/\\*\\+[\\s\\S]*?\\*/", Some(&["Comment", "Multiline", "Hint"])),
    ("(--|# ).*?(\\r\\n|\\r|\\n|$)", Some(&["Comment", "Single"])),
    ("/\\*[\\s\\S]*?\\*/", Some(&["Comment", "Multiline"])),
    ("(\\r\\n|\\r|\\n)", Some(&["Text", "Whitespace", "Newline"])),
    ("\\s+?", Some(&["Text", "Whitespace"])),
    (":=", Some(&["Assignment"])),
    ("::", Some(&["Punctuation"])),
    ("\\*", Some(&["Wildcard"])),
    ("`(``|[^`])*`", Some(&["Name"])),
    ("´(´´|[^´])*´", Some(&["Name"])),
    ("((?<![\\w\\\"\\$])\\$(?:[_A-ZÀ-Ü]\\w*)?\\$)[\\s\\S]*?\\1", Some(&["Literal"])),
    ("\\?", Some(&["Name", "Placeholder"])),
    ("%(\\(\\w+\\))?s", Some(&["Name", "Placeholder"])),
    ("(?<!\\w)[$:?]\\w+", Some(&["Name", "Placeholder"])),
    ("\\\\\\w+", Some(&["Generic", "Command"])),
    ("(CASE|IN|VALUES|USING|FROM|AS)\\b", Some(&["Keyword"])),
    ("(@|##|#)[A-ZÀ-Ü]\\w+", Some(&["Name"])),
    ("[A-ZÀ-Ü]\\w*(?=\\s*\\.)", Some(&["Name"])),
    ("(?<=\\.)[A-ZÀ-Ü]\\w*", Some(&["Name"])),
    ("[A-ZÀ-Ü]\\w*(?=\\()", Some(&["Name"])),
    ("-?0x[\\dA-F]+", Some(&["Literal", "Number", "Hexadecimal"])),
    ("-?\\d+(\\.\\d+)?E-?\\d+", Some(&["Literal", "Number", "Float"])),
    ("(?![_A-ZÀ-Ü])-?(\\d+(\\.\\d*)|\\.\\d+)(?![_A-ZÀ-Ü])", Some(&["Literal", "Number", "Float"])),
    ("(?![_A-ZÀ-Ü])-?\\d+(?![_A-ZÀ-Ü])", Some(&["Literal", "Number", "Integer"])),
    ("'(''|\\\\'|[^'])*'", Some(&["Literal", "String", "Single"])),
    ("\"(\"\"|\\\\\"|[^\"])*\"", Some(&["Literal", "String", "Symbol"])),
    ("(\"\"|\".*?[^\\\\]\")", Some(&["Literal", "String", "Symbol"])),
    ("(?<![\\w\\])])(\\[[^\\]\\[]+\\])", Some(&["Name"])),
    ("((LEFT\\s+|RIGHT\\s+|FULL\\s+)?(INNER\\s+|OUTER\\s+|STRAIGHT\\s+)?|(CROSS\\s+|NATURAL\\s+)?)?JOIN\\b", Some(&["Keyword"])),
    ("END(\\s+IF|\\s+LOOP|\\s+WHILE)?\\b", Some(&["Keyword"])),
    ("IF\\s+(NOT\\s+)?EXISTS\\b", Some(&["Keyword"])),
    ("NOT\\s+NULL\\b", Some(&["Keyword"])),
    ("(ASC|DESC)(\\s+NULLS\\s+(FIRST|LAST))?\\b", Some(&["Keyword", "Order"])),
    ("(ASC|DESC)\\b", Some(&["Keyword", "Order"])),
    ("NULLS\\s+(FIRST|LAST)\\b", Some(&["Keyword", "Order"])),
    ("UNION\\s+ALL\\b", Some(&["Keyword"])),
    ("CREATE(\\s+OR\\s+REPLACE)?\\b", Some(&["Keyword", "DDL"])),
    ("DOUBLE\\s+PRECISION\\b", Some(&["Name", "Builtin"])),
    ("GROUP\\s+BY\\b", Some(&["Keyword"])),
    ("ORDER\\s+BY\\b", Some(&["Keyword"])),
    ("PRIMARY\\s+KEY\\b", Some(&["Keyword"])),
    ("HANDLER\\s+FOR\\b", Some(&["Keyword"])),
    ("GO(\\s\\d+)\\b", Some(&["Keyword"])),
    ("(LATERAL\\s+VIEW\\s+)(EXPLODE|INLINE|PARSE_URL_TUPLE|POSEXPLODE|STACK)\\b", Some(&["Keyword"])),
    ("(AT|WITH')\\s+TIME\\s+ZONE\\s+'[^']+'", Some(&["Keyword", "TZCast"])),
    ("(NOT\\s+)?(LIKE|ILIKE|RLIKE)\\b", Some(&["Operator", "Comparison"])),
    ("(NOT\\s+)?(REGEXP)(\\s+(BINARY))?\\b", Some(&["Operator", "Comparison"])),
    ("\\w[$#\\w]*", None),
    ("[;:()\\[\\],\\.]", Some(&["Punctuation"])),
    ("(\\->>?|#>>?|@>|<@|\\?\\|?|\\?&|\\-|#\\-)", Some(&["Operator"])),
    ("[<>=~!]+", Some(&["Operator", "Comparison"])),
    ("[+/@#%^&|^-]+", Some(&["Operator"])),
];
